### ISSUE TITLE
Pascal VOC style output

### ISSUE THREAD

**Issue by helq2612** [weii41392/AQT#1]
Great work!

Could you please share the scripts to output per category AP (Tab 1 & 2) in the paper?

Thanks!

**Comment by weii41392** [comment]
Hi, thanks for your interest in our work!

I don't have the evaluation script we used at this time, but it was adapted from this [snippet](https://github.com/kimyoon-young/centerNet-deep-sort/blob/9bd5159/tools/cocoeval.py#L458-L464).

Hope this helps!

**Comment by helq2612** [comment]
Hi @weii41392 , thank you for your reply! It works (btw, in util/anno_convert.py, the last two categories should be "motorcycle" and "bicycle"):
`
category : 0 : 0.49328261486631575
category : 1 : 0.5233313784074675
category : 2 : 0.6444463569020743
category : 3 : 0.27690485998153613
category : 4 : 0.5374067788693834
category : 5 : 0.46543954793357317
category : 6 : 0.3599048002187429
category : 7 : 0.463837716531337
(all categories) mAP : 0.4705692567138038
`

**Comment by sysuzgg** [comment]
> Hi @weii41392 , thank you for your reply! It works (btw, in util/anno_convert.py, the last two categories should be "motorcycle" and "bicycle"): `category : 0 : 0.49328261486631575 category : 1 : 0.5233313784074675 category : 2 : 0.6444463569020743 category : 3 : 0.27690485998153613 category : 4 : 0.5374067788693834 category : 5 : 0.46543954793357317 category : 6 : 0.3599048002187429 category : 7 : 0.463837716531337 (all categories) mAP : 0.4705692567138038`

Could you please share the scripts to output per category AP?
