### ISSUE TITLE
Poor performance on cityscapes to foggy_cityscapes

### ISSUE THREAD

**Issue by helq2612** [weii41392/AQT#3]
Hi  @weii41392,

I tried to reproduce AQT on cityscapes to foggy_cityscapes, and used your provided bash script (8GPUs). After 50 epochs training, the results is AP50=36.4. Is there some thing that I missed?

Here are the AP50s for each training epoch:
000, APbbox_50= 0.0575
001, APbbox_50= 0.1251
002, APbbox_50= 0.1445
003, APbbox_50= 0.1749
004, APbbox_50= 0.1848
005, APbbox_50= 0.1972
006, APbbox_50= 0.2218
007, APbbox_50= 0.2197
008, APbbox_50= 0.2198
009, APbbox_50= 0.2294
010, APbbox_50= 0.2225
011, APbbox_50= 0.2478
012, APbbox_50= 0.2477
013, APbbox_50= 0.2562
014, APbbox_50= 0.2607
015, APbbox_50= 0.2581
016, APbbox_50= 0.2716
017, APbbox_50= 0.2664
018, APbbox_50= 0.2692
019, APbbox_50= 0.2701
020, APbbox_50= 0.2505
021, APbbox_50= 0.2794
022, APbbox_50= 0.2769
023, APbbox_50= 0.2993
024, APbbox_50= 0.3043
025, APbbox_50= 0.2925
026, APbbox_50= 0.2757
027, APbbox_50= 0.2717
028, APbbox_50= 0.2877
029, APbbox_50= 0.3003
030, APbbox_50= 0.2919
031, APbbox_50= 0.2946
032, APbbox_50= 0.2951
033, APbbox_50= 0.3072
034, APbbox_50= 0.3013
035, APbbox_50= 0.3170
036, APbbox_50= 0.3235
037, APbbox_50= 0.3142
038, APbbox_50= 0.3083
039, APbbox_50= 0.3416
040, APbbox_50= 0.3520
041, APbbox_50= 0.3540
042, APbbox_50= 0.3509
043, APbbox_50= 0.3503
044, APbbox_50= 0.3562
045, APbbox_50= 0.3595
046, APbbox_50= 0.3553
047, APbbox_50= 0.3587
048, APbbox_50= 0.3658
049, APbbox_50= 0.3644

**Comment by helq2612** [comment]
Sorry I got a small bug in the data convert. I can successfully reproduce AQT on C->F. The AP50 I got is 47.2.

**Comment by peterstratton** [comment]
Hey I fixed this issue, but my AP50 is still way below the reported AP after training for 50 epochs, did you change anything else?
